kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

# @schema $ref: charts/security-profiles-operator/values.schema.json
# @schema additionalProperties: true
# -- Values passed through to the upstream chart. For available options, see the [upstream values.yaml](https://github.com/kubernetes-sigs/security-profiles-operator/blob/v1.0.1/deploy/helm/values.yaml).
# @default -- See [values.yaml](./values.yaml#L17)
security-profiles-operator:
  # @schema hidden
  spoImage:
    registry: registry.k8s.io
    repository: security-profiles-operator/security-profiles-operator
    tag: v1.0.1

  # @schema hidden
  selinux:
    enable: true
    customTemplatesConfigMap: udica-templates
    options:
      allowedTypes:
        - kernel_t
        - security_t

  # @schema hidden
  daemon:
    # @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.Toleration
    tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
        operator: Exists
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        operator: Exists
      - key: node.kubernetes.io/not-ready
        effect: NoSchedule
        operator: Exists
      - key: node.cilium.io/agent-not-ready
        effect: NoSchedule
        operator: Exists
      - key: ebs.csi.aws.com/agent-not-ready
        effect: NoExecute
        operator: Exists

  # @schema hidden
  # @schema additionalProperties: true
  # @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSecurityContext
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
