# This file is a Helm values file for the security-profiles-operator chart.
#
# To learn more about how to configure your app on your cluster
# and override the default values in here, visit:
#
#   https://docs.giantswarm.io/tutorials/fleet-management/app-platform/app-configuration/#basic-values-merging-example
#
image:
  name: "giantswarm/security-profiles-operator"
  tag: ""
registry:
  domain: gsoci.azurecr.io

# @schema $ref: charts/security-profiles-operator/values.schema.json
# -- Values passed through to the upstream chart. For available options, see the [upstream values.yaml](https://github.com/kubernetes-sigs/security-profiles-operator/blob/v0.10.1/deploy/helm/values.yaml).
security-profiles-operator: {}
